M48
; DRILL file {KiCad 7.0.6} date Mon Apr 22 22:59:52 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-04-22T22:59:52-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.250
%
G90
G05
T1
X106.6Y-43.25
X106.6Y-48.25
T2
X27.95Y-30.17
X27.95Y-40.33
X28.0Y-57.42
X28.0Y-67.58
X28.0Y-72.42
X28.0Y-82.58
T0
M30
